packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - fsevents
  - lefthook
  - tailwindcss
  - weapp-tailwindcss
