packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tarojs/binding'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - fsevents
  - lefthook
  - swiper
  - weapp-tailwindcss
